---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    env:
      DJANGO_KEY: ${{ secrets.DJANGO_KEY }}
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Test env
        run: python -c 'import os; print(os.environ)'
        env:
            DJANGO_KEY: ${{ secrets.DJANGO_KEY }}
      - name: Test inline env vars for python
        run: DJANGO_KEY=${{ secrets.DJANGO_KEY }} python -c 'import os;print\(os.environ\)'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c 'flake8'


